import { getArcadeData, saveToRealtimeDB } from '/config/firebase-config.js';
import { watchAuthState } from '/config/auth.js';
import { globalTheme, applyTheme, databaseCache } from './realm-engine.js';

let allSparks = [];
let currentIndex = -1;
let currentId = '';
let userId = '';

console.log(`%c YERTAL SPARKS LOADED | ${new Date().toLocaleDateString()} @ 10:36:00 `, "background: var(--branding-color); color: var(--bg-color); font-weight: bold; border: 1px solid var(--branding-color); padding: 4px;");
/*
 * Objective: Capture live UI state from the simulation iframe.
 * Task: Directly update the spark object's parameter_map with current UI values.
 */
function syncUIToSessionMap(spark) {
    console.group("%c[SYNC DEBUG] 🔍 Distilling UI to Spark Object...", "color: #ffca28; font-weight: bold;");

    const settings = databaseCache?.settings || {};
    const blueprints = settings["arcade-current-types"];
    const blueprint = Array.isArray(blueprints) ? blueprints[spark.index] : null;

    if (!blueprint || !blueprint.parameter_map) {
        console.warn("[SYNC] ❌ No blueprint schema found for index:", spark.index);
        console.groupEnd();
        return;
    }

    const iframeDoc = document.getElementById('content-frame')?.contentWindow?.document;
    if (!iframeDoc) {
        console.error("[SYNC] ❌ Critical: Cannot access iframe document.");
        console.groupEnd();
        return;
    }

    // Ensure the spark has a parameter_map to write to
    if (!spark.parameter_map) spark.parameter_map = {};

    const schemaKeys = Object.keys(blueprint.parameter_map);
    
    schemaKeys.forEach(key => {
        const input = iframeDoc.getElementById(key);
        if (input) {
            let val = input.value;
            const type = input.type;

            // Type-specific extraction
            if (type === 'range' || type === 'number' || type === 'hidden') {
                val = parseFloat(val);
            } else if (type === 'checkbox') {
                val = input.checked;
            }

            // DIRECT MUTATION: Update the spark memory object
            if (spark.parameter_map[key] !== val) {
                console.log(`%c[SYNC] Update: ${key} | ${spark.parameter_map[key]} -> ${val}`, "color: #4caf50; font-weight: bold;");
                spark.parameter_map[key] = val;
            }
        }
    });

    console.log("[SYNC] Distillation Complete. Spark Memory is now current.");
    console.groupEnd();
}

/*
 * Standardizes raw Spark code to fit the responsive Laboratory Viewport.
 * @param {Object} spark - The spark data object from the DB.
 * @returns {string} - The complete HTML string for the iframe.
 */
function wrapCodeInLaboratory(spark) {
    const activeCode = spark.code || (spark.data ? spark.data.code : null) || spark.html || (typeof spark === 'string' ? spark : "");

    return `
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <style>
                /* Prevent the 'Double Scrollbar' and Clipping */
                body, html { 
                    margin: 0; 
                    padding: 0; 
                    width: 100%; 
                    height: 100%; 
                    overflow: hidden; /* Critical: Stops the Spark from overflowing the Lab */
                    background: transparent; 
                    display: flex; 
                    flex-direction: column;
                }

                #user-code-wrapper {
                    flex: 1; /* Occupies all available space in the Lab */
                    width: 100%;
                    height: 100%;
                    display: flex;
                    flex-direction: column;
                    justify-content: center;
                    align-items: center;
                    position: relative;
                    box-sizing: border-box;
                }

                /* Standardizes any canvas generated by Gemini to fit within the viewport */
                #user-code-wrapper canvas { 
                    max-width: 100% !important; 
                    max-height: 100% !important;
                    object-fit: contain; 
                    box-sizing: border-box;
                }
            </style>
        </head>
        <body>
            <div id="user-code-wrapper">
                ${activeCode}
            </div>

            <script>
                (function() {
                    const wrapper = document.getElementById('user-code-wrapper');

function syncDimensions() {
                        const canvases = document.querySelectorAll('canvas');
                        const bounds = wrapper.getBoundingClientRect();

                        canvases.forEach(canvas => {
                            if (canvas.width !== bounds.width || canvas.height !== bounds.height) {
 // FUTURE-PROOF CONTEXT DETECTION:
 // Check for active 2D properties instead of blacklisting specific 3D tokens.
 // If a context isn't strictly 2D, forcing a 2D pull returns null and avoids context mutation errors.
 const isStrict2D = canvas.getContext('2d') && !canvas.classList.contains('p5Canvas');
 
 if (!isStrict2D) {
 // Let WebGL, WebGL2, WebGPU, and advanced engines scale gracefully via the global resize event
 return;
 }

                                // Save current drawing to prevent flicker/loss
                                const tempCtx = canvas.getContext('2d');
                                let tempImage = null;
                                if (tempCtx) {
                                    tempImage = canvas.toDataURL();
                                }

                                canvas.width = bounds.width;
                                canvas.height = bounds.height;

                                if (tempImage) {
                                    const img = new Image();
                                    img.src = tempImage;
                                    img.onload = () => canvas.getContext('2d').drawImage(img, 0, 0, bounds.width, bounds.height);
                                }
                            }
                        });

                        // Safeguard for Gemini scripts that leverage p5.js execution layers
                        if (typeof resizeCanvas === 'function') {
                            resizeCanvas(bounds.width, bounds.height);
                        }

                        // Notify internal scripts (Three.js/WebGPU/P5) that the Lab has resized
                        window.dispatchEvent(new Event('resize'));
                    }
                    // ResizeObserver is more reliable than window.onresize for iframe/container changes
                    const ro = new ResizeObserver(() => {
 console.log("[LAB MONITOR] ResizeObserver triggered via wrapper mutation.");
                        requestAnimationFrame(syncDimensions);
                    });

                    ro.observe(wrapper);

                    // Initial sync once everything is parsed
                    window.addEventListener('load', () => {
 console.log("[LAB MONITOR] Window load event fired. Initializing syncDimensions layout check.");
                        syncDimensions();
                    });
                })();
            </script>
        </body>
        </html>
    `;
}

/*
 * Objective: Render Spark content and reset HUD visuals.
 * Task: Initialize playable states and reset timing/progress for the new session.
 */
function loadSpark(spark) {
    const container = document.getElementById('spark-content-container');
    const titleEl = document.getElementById('active-spark-name');
    const overlay = document.getElementById('spark-title-overlay');
    const hudStatus = document.getElementById('hud-status');
    const fallbackBtn = document.getElementById('fallback-url-btn');
    
    // 0. HUD CONTROL INITIALIZATION
    window.currentSpark = spark;
    const playPauseBtn = document.getElementById('play-pause-btn');
    const playIcon = document.getElementById('play-icon');
    const curTimeEl = document.getElementById('current-time');
    const totTimeEl = document.getElementById('total-duration');
    const progressFill = document.getElementById('media-progress-bar');

    // CRITICAL FOR TIMING: Reset visuals to zero state immediately
    if (curTimeEl) curTimeEl.textContent = "0:00";
    if (totTimeEl) totTimeEl.textContent = "0:00";
    if (progressFill) progressFill.style.width = "0%";

    // Intelligent Type Detection
    const playableIDs = ['movies', 'videos', 'veo-video', 'arcade-logic', 'games', 'physics-lab', 'optics'];
    const isPlayable = playableIDs.includes(spark.template_type?.toLowerCase()) || 
                       (spark.link && (spark.link.includes('youtube.com') || spark.link.includes('vimeo.com')));

    if (playPauseBtn) {
        playPauseBtn.style.opacity = isPlayable ? '1' : '0.3';
        playPauseBtn.style.pointerEvents = isPlayable ? 'auto' : 'none';
        
        // Default to 'Pause' icon because simulations/videos usually autoplay
        if (playIcon) {
            playIcon.classList.remove('fa-play');
            playIcon.classList.add('fa-pause');
        }
    }

    // 1. IDENTITY & THEME
    if (typeof databaseCache !== 'undefined') {
        applyTheme(globalTheme);
    }
    
    console.log(`%c[YERTAL LAB] Loading Spark: ${spark.name}`, "color: #00f2ff; font-weight: bold;");
        
    container.style.opacity = '0';
    container.innerHTML = '';
    if (hudStatus) hudStatus.textContent = "INITIALIZING...";

    titleEl.textContent = spark.name;
    overlay.style.opacity = "1";
    setTimeout(() => { overlay.style.opacity = "0"; }, 3000);

    // 2. CONTENT INJECTION
    if (spark.link) {
        let finalUrl = spark.link;
        if (finalUrl.includes('youtube.com/watch?v=')) {
            finalUrl = finalUrl.replace('watch?v=', 'embed/') + "?autoplay=1&mute=1&enablejsapi=1";
        }
        
        container.innerHTML = `<iframe id="content-frame" src="${finalUrl}" allow="autoplay; fullscreen"></iframe>`;
        container.style.opacity = '1';
        
    } else {
        const iframe = document.createElement('iframe');
        iframe.id = "content-frame";
        // allow-same-origin is critical for persistence if scripts interact with parent
        iframe.setAttribute('sandbox', 'allow-scripts allow-same-origin allow-forms');
        
        container.appendChild(iframe);

        // Wrap the code
        const standardizedCode = wrapCodeInLaboratory(spark);
        
        /*
         * REVERT TO DOCUMENT.WRITE:
         * Using the fixed template (block comments only), document.write provides 
         * the most stable injection method for dynamic hydration.
         */
        try {
            const doc = iframe.contentWindow.document;
            doc.open();
            doc.write(standardizedCode);
            doc.close();
        } catch (err) {
            console.error("[SYSTEM] Document write failed:", err);
        }

        if (fallbackBtn) fallbackBtn.classList.add('hidden');

        iframe.onload = () => {
            container.style.opacity = '1';
            if (hudStatus) hudStatus.textContent = "SPARK FULLY LOADED";
        };
    }
}

/*
 * Objective: Change viewports to adjacent spark structures.
 * Task: Maintain state continuity across transitions by preserving realm configuration URL parameters.
 */
function navigate(dir) {
    if (!allSparks || allSparks.length === 0) return;

    currentIndex = (currentIndex + dir + allSparks.length) % allSparks.length;
    
    const nextSpark = allSparks[currentIndex];
    
    // Read and preserve active realm parameter
    const currentParams = new URLSearchParams(window.location.search);
    const realmParam = currentParams.get('realm');
    
    let newUrl = `${window.location.pathname}?current=${currentId}&spark=${nextSpark.id}`;
    if (realmParam) {
        newUrl += `&realm=${realmParam}`;
    }
    
    window.history.pushState({path: newUrl}, '', newUrl);
    console.log(`navigation detected direction=${dir} currentIndex=${currentIndex}`);
    
    const freshlyAssembled = assembleSpark(nextSpark);
    window.currentSpark = freshlyAssembled;
    loadSpark(freshlyAssembled);
}

function toggleZen() {
    document.body.classList.toggle('zen-active');
}

function togglePlayPause() {
    window.dispatchEvent(new CustomEvent('toggleMedia'));
    const icon = document.getElementById('play-icon');
    if (icon) {
        icon.classList.toggle('fa-play');
        icon.classList.toggle('fa-pause');
    }
}

/*
 * Objective: Initialize HUD and navigation interactions.
 * Task: Restrict navigation to mouse-only via side zones and reserve arrow keys for viewport gameplay.
 * Task: Integrate Session Map resets on navigation and exit.
 */
function setupInteractions(currentUid, spark) {
    // 1. Navigation: Mouse-Only via side zones
    const prevZone = document.getElementById('prev-zone');
    const nextZone = document.getElementById('next-zone');

    if (prevZone) {
        prevZone.onclick = (e) => {
            e.stopPropagation();
            e.preventDefault();
            console.log("[NAV] Navigating to Previous Spark...");
            navigate(-1);
        };
    }

    if (nextZone) {
        nextZone.onclick = (e) => {
            e.stopPropagation();
            e.preventDefault();
            console.log("[NAV] Navigating to Next Spark...");
            navigate(1);
        };
    }

    // 2. HUD & Cover Bindings
    const editBtn = document.getElementById('edit-spark-btn');

    if (editBtn) {
        const isOwner = currentUid && spark && spark.owner === currentUid;
        const userProfile = databaseCache.users?.[currentUid]?.profile || {};
        const isSuperUser = userProfile.superuser === true;

        if (isOwner || isSuperUser) {
            editBtn.style.display = 'flex';
            editBtn.onclick = (e) => {
                e.stopPropagation();
                openSparkEditor(window.currentSpark || spark);
            };
        } else {
            editBtn.style.display = 'none';
        }
    }

    // 3. UI Toggles & Media Controls
    const zenBtn = document.getElementById('zen-btn');
    if (zenBtn) zenBtn.onclick = toggleZen;

    const exitZenBtn = document.getElementById('exit-zen-btn');
    if (exitZenBtn) {
        exitZenBtn.onclick = (e) => {
            e.stopPropagation();
            toggleZen();
        };
    }

    const playPauseBtn = document.getElementById('play-pause-btn');
    if (playPauseBtn) {
        playPauseBtn.onclick = (e) => {
            e.stopPropagation();
            togglePlayPause();
        };
    }

    const contentContainer = document.getElementById('spark-content-container');
    if (contentContainer) {
        contentContainer.onclick = (e) => {
            togglePlayPause();
        };
    }

    // 4. Reload Logic: Now tracking window.currentSpark dynamically
    const reloadBtn = document.getElementById('reload-spark-btn');
    if (reloadBtn) {
        reloadBtn.onclick = () => {
            const activeSpark = window.currentSpark || spark;
            if (activeSpark) {
                console.group("🔄 RELOAD AUDIT");
                // 1. Sync
                syncUIToSessionMap(activeSpark);
                // 2. Assemble
                const freshlyAssembledSpark = assembleSpark(activeSpark);
                // 3. Load
                window.currentSpark = freshlyAssembledSpark;
                loadSpark(freshlyAssembledSpark);
                console.groupEnd();
            }
        };
    }

    // 5. Fallback URL Binding
    const fallbackBtn = document.getElementById('fallback-url-btn');
    if (fallbackBtn) {
        fallbackBtn.onclick = () => {
            const activeSpark = window.currentSpark || spark;
            if (activeSpark && activeSpark.link) {
                window.open(activeSpark.link, '_blank');
            }
        };
    }

    // 6. Exit Logic: Return to Arcade
    const exitBtn = document.getElementById('exit-btn');
    if (exitBtn) {
        exitBtn.addEventListener('click', (e) => {
            e.preventDefault();
            e.stopPropagation();

            const params = new URLSearchParams(window.location.search);
            const activeProfile = databaseCache.users?.[currentUid]?.profile || {};
            const realmId = params.get('realm') || activeProfile.active_realm_id || 'realm-20260804-1785866761042';

            const container = document.getElementById('spark-content-container');
            if (container) container.innerHTML = '';

            console.log("[SYSTEM] Exiting to Arcade...");
            window.location.href = `/arcade/index.html?realm=${realmId}`;
        }, true);
    }

    // 8. Keyboard Shortcuts
    window.onkeydown = (e) => {
        const key = e.key.toLowerCase();

        if (key === 'z' || key === 'escape') {
            toggleZen();
        }

        // Ctrl+R Logic: Now tracks live global target execution context
        if (key === 'r' && e.ctrlKey) {
            e.preventDefault();
            const activeSpark = window.currentSpark || spark;
            if (activeSpark) {
                syncUIToSessionMap(activeSpark);
                const freshlyAssembled = assembleSpark(activeSpark);
                window.currentSpark = freshlyAssembled;
                loadSpark(freshlyAssembled);
            }
        }

        if (key === ' ' && e.target.tagName !== 'INPUT' && e.target.tagName !== 'TEXTAREA') {
            e.preventDefault();
            togglePlayPause();
        }
    };

    // 9. Auto-Focus Viewport
    const iframe = document.querySelector('#spark-content-container iframe');
    if (iframe) iframe.focus();
}

function assembleSpark(spark) {
    if ((spark.code || spark.link) && (spark.index === undefined || spark.index === null)) {
        return spark;
    }

    const settings = databaseCache?.settings || {};
    const blueprints = settings["arcade-current-types"];
    const blueprint = Array.isArray(blueprints) ? blueprints[spark.index] : null;

    if (!blueprint) {
        console.error(`[ASSEMBLER] ❌ FAILED: No blueprint found at index: ${spark.index}`);
        return spark;
    }

    // --- THE HIERARCHY OF TRUTH ---
    // Layer 1: Blueprint Defaults
    // Layer 2: User Spark Node (Saved state)
    // Layer 3: Live Session (Current UI state)
    const finalParameters = { 
        ...(blueprint.parameter_map || {}), 
        ...(spark.parameter_map || {})
    };

    console.groupCollapsed(`[ASSEMBLER] 🛠️ Assembling: ${spark.name}`);
    console.log("Hierarchy Result:", finalParameters);

    let hydratedCode = blueprint.template || "";

    if (hydratedCode) {
        // Iterate through the keys defined in the BLUEPRINT to ensure we don't miss anything
        const schemaKeys = Object.keys(blueprint.parameter_map || finalParameters);
        
        schemaKeys.forEach(key => {
            let value = finalParameters[key];

            // Handle Arrays/Objects cleanly based on nesting types
            if (value !== null && typeof value === 'object') {
                if (Array.isArray(value)) {
                    // Maintain original logic for sequential arrays
                    value = JSON.stringify(value).replace(/"/g, "'").replace(/'/g, "&apos;");
                } else {
                    // Deep nested nodes/objects require raw, unescaped JSON text
                    value = JSON.stringify(value);
                }
            }

            const regex = new RegExp(`{{\\s*${key}\\s*(?:\\|\\|\\s*[^}]+)?}}`, 'g');
            
            if (hydratedCode.match(regex)) {
                // This is the moment of truth: check the log for this specific replacement
                console.log(`[BAKING] {{${key}}} -> ${value}`);
                hydratedCode = hydratedCode.replace(regex, () => value);
            }
        });
    }

    console.groupEnd();

    // We return a NEW object to avoid mutating the original reference too early
    return {
        ...spark,
        code: hydratedCode,
        parameter_map: finalParameters 
    };
}

/*
 * Objective: Hydrate a blueprint template with the established hierarchy of truth.
 * Task: Ensure session values (Layer 3) take absolute precedence during string replacement.
 */
function prevAssembleSpark(spark) {
    if ((spark.code || spark.link) && (spark.index === undefined || spark.index === null)) {
        return spark;
    }

    const settings = databaseCache?.settings || {};
    const blueprints = settings["arcade-current-types"];
    const blueprint = Array.isArray(blueprints) ? blueprints[spark.index] : null;

    if (!blueprint) {
        console.error(`[ASSEMBLER] ❌ FAILED: No blueprint found at index: ${spark.index}`);
        return spark;
    }

    // --- THE HIERARCHY OF TRUTH ---
    // Layer 1: Blueprint Defaults
    // Layer 2: User Spark Node (Saved state)
    // Layer 3: Live Session (Current UI state)
    const finalParameters = { 
        ...(blueprint.parameter_map || {}), 
        ...(spark.parameter_map || {})
    };

    console.groupCollapsed(`[ASSEMBLER] 🛠️ Assembling: ${spark.name}`);
    console.log("Hierarchy Result:", finalParameters);

    let hydratedCode = blueprint.template || "";

    if (hydratedCode) {
        // Iterate through the keys defined in the BLUEPRINT to ensure we don't miss anything
        const schemaKeys = Object.keys(blueprint.parameter_map || finalParameters);
        
        schemaKeys.forEach(key => {
            let value = finalParameters[key];

            // Handle Arrays/Objects
            if (value !== null && typeof value === 'object') {
                value = JSON.stringify(value).replace(/"/g, "'").replace(/'/g, "&apos;");
            }

            const regex = new RegExp(`{{\\s*${key}\\s*(?:\\|\\|\\s*[^}]+)?}}`, 'g');
            
            if (hydratedCode.match(regex)) {
                // This is the moment of truth: check the log for this specific replacement
                console.log(`[BAKING] {{${key}}} -> ${value}`);
                hydratedCode = hydratedCode.replace(regex, () => value);
            }
        });
    }

    console.groupEnd();

    // We return a NEW object to avoid mutating the original reference too early
    return {
        ...spark,
        code: hydratedCode,
        parameter_map: finalParameters 
    };
}

watchAuthState(async (user) => {
    console.log("%c[AUTH] State Changed", "color: #00ff00;");
    if (!user) return;

    userId = user.uid; 
    // Load the spark for the realm, current, spark defined in the URL
    const params = new URLSearchParams(window.location.search);
    const realmId = params.get('realm') || 'yertal-arcade'; 
    currentId = params.get('current');
    const initialSparkId = params.get('spark');

    // 1. Fetch data if missing or if the realm isn't loaded
    if (!databaseCache || Object.keys(databaseCache).length === 0 || !databaseCache.realms?.[realmId]) {
        console.log("[CACHE] Cache miss for realm:", realmId, ". Fetching...");
        const freshData = await getArcadeData(); 
        Object.assign(databaseCache, freshData);
    }

    // 2. Fetch target realm record directly
    const realmRecord = databaseCache?.realms?.[realmId];

    if (!realmRecord || !realmRecord.currents) {
        console.warn("[DATA] Currents missing for realm:", realmId);
        return;
    }

    // Evaluate Ownership & Realm-level Privacy
    const isOwner = realmRecord.realm_ownerid === user.uid;
    const isRealmPrivate = realmRecord.realm_privacy === 'private';

    // 3. Ensure the specific current exists under the realm
    const currents = realmRecord.currents || {};
    let path = currents[currentId];

    if (!path) {
        // Fallback to first current accessible by the user
        const fallbackCurrent = Object.values(currents).find(c => isOwner || c.privacy !== 'private');
        if (fallbackCurrent) {
            console.warn("[DATA] Redirecting to fallback current infrastructure.");
            path = fallbackCurrent;
            currentId = path.id;
        } else {
            console.error("[DATA] No accessible record for current:", currentId);
            document.getElementById('active-spark-name').textContent = "ACCESS DENIED: RESTRICTED CURRENT";
            const container = document.getElementById('spark-content-container');
            if (container) {
                container.innerHTML = `<div style="text-align: center; padding: 5rem 0; color: var(--branding-text-color); opacity: 0.6; font-style: italic;">ACCESS DENIED: RESTRICTED NODE</div>`;
            }
            return;
        }
    }

    const isCurrentPrivate = path.privacy === 'private';

    // SECURITY CHECK 1: Realm or Current privacy gate for visitors
    if (!isOwner && (isRealmPrivate || isCurrentPrivate)) {
        console.warn("[SECURITY] Access denied to private realm or current node for visitor.");
        document.getElementById('active-spark-name').textContent = "ACCESS DENIED: PRIVATE NODE";
        const container = document.getElementById('spark-content-container');
        if (container) {
            container.innerHTML = `<div style="text-align: center; padding: 5rem 0; color: var(--branding-text-color); opacity: 0.6; font-style: italic;">ACCESS DENIED: THIS NODE IS PRIVATE</div>`;
        }
        return;
    }

    // 4. Load & Filter Sparks
    const sparksObj = path.sparks || {};
    const rawSparks = Object.values(sparksObj).sort((a, b) => (a.created || 0) - (b.created || 0));

    // FILTER NAVIGATION ARRAY: Non-owners only receive public sparks
    allSparks = isOwner ? rawSparks : rawSparks.filter(s => s.privacy !== 'private');
    
    // Use the ID from the URL or fallback to the first accessible spark
    currentIndex = allSparks.findIndex(s => s.id === initialSparkId);

    let activeSpark = null;
    if (currentIndex !== -1) {
        activeSpark = allSparks[currentIndex];
    } else if (allSparks.length > 0) {
        activeSpark = allSparks[0];
        currentIndex = 0;
    }

    // SECURITY CHECK 2: Validate target active spark privacy
    if (activeSpark) {
        if (!isOwner && activeSpark.privacy === 'private') {
            console.warn("[SECURITY] Direct URL access denied to private spark.");
            document.getElementById('active-spark-name').textContent = "ACCESS DENIED: PRIVATE SPARK";
            const container = document.getElementById('spark-content-container');
            if (container) {
                container.innerHTML = `<div style="text-align: center; padding: 5rem 0; color: var(--branding-text-color); opacity: 0.6; font-style: italic;">ACCESS DENIED: THIS SPARK IS PRIVATE</div>`;
            }
            return;
        }

        const preparedSpark = assembleSpark(activeSpark);
        loadSpark(preparedSpark);
    } else {
        document.getElementById('active-spark-name').textContent = "NO ACCESSIBLE SPARKS";
        const container = document.getElementById('spark-content-container');
        if (container) {
            container.innerHTML = `<div style="text-align: center; padding: 5rem 0; color: var(--branding-text-color); opacity: 0.6; font-style: italic;">NO PUBLIC SPARKS AVAILABLE IN THIS CURRENT</div>`;
        }
    }

    setupInteractions(user.uid, activeSpark);
});
window.addEventListener('message', (event) => {
    // 1. Security check: Ensure we have data
    if (!event.data || event.data.type !== 'TICKER_UPDATE') return;

    const { currentTime, duration } = event.data;
    
    // 2. Select the HTML elements from your spark.html
    const curTimeEl = document.getElementById('current-time');
    const totTimeEl = document.getElementById('total-duration');
    const progressFill = document.getElementById('media-progress-bar');

    // 3. Formatter: Converts seconds (65) to string (01:05)
    const format = (seconds) => {
        const mins = Math.floor(seconds / 60);
        const secs = Math.floor(seconds % 60);
        return `${mins}:${secs.toString().padStart(2, '0')}`;
    };

    // 4. Update the HUD
    if (curTimeEl) curTimeEl.textContent = format(currentTime);
    if (totTimeEl) totTimeEl.textContent = format(duration);
    
    if (progressFill && duration > 0) {
        const percent = (currentTime / duration) * 100;
        progressFill.style.width = `${percent}%`;
    }
});

async function openSparkEditor(spark) {
    if (!spark) return;

    // 0. HIDE CONTROL PANEL WHILE MODAL IS ACTIVE
    const controlPanel = document.getElementById('hud-controls') || 
                         document.getElementById('controls') || 
                         document.getElementById('hud-status')?.closest('div[style*="position"], div[class*="control"]');
    
    if (controlPanel) {
        controlPanel.style.display = 'none';
    }

    const restoreUIAndClose = () => {
        // Clean up hover preview tooltip if active
        const tooltip = document.getElementById('spark-image-magnifier-tooltip');
        if (tooltip) tooltip.remove();

        const modal = document.getElementById('spark-editor-modal');
        if (modal) modal.remove();
        if (controlPanel) controlPanel.style.display = '';
    };

    window.closeSparkEditor = restoreUIAndClose;

    // 1. RESET GLOBAL SELECTIONS to prevent data-bleeding between sparks
    window.selectedCover = null;
    window.selectedPhotographer = null;

    let editorOverlay = document.getElementById('spark-editor-modal');
    if (!editorOverlay) {
        editorOverlay = document.createElement('div');
        editorOverlay.id = 'spark-editor-modal';
        editorOverlay.style.cssText = `
            position: fixed; top: 0; left: 0; width: 100vw; height: 100vh;
            background: rgba(0, 0, 0, 0.88); backdrop-filter: blur(12px);
            display: flex; justify-content: center; align-items: center; z-index: 100000;
        `;
        document.body.appendChild(editorOverlay);
    }

    // CREATE DYNAMIC MAGNIFIER TOOLTIP CONTAINER (RESIZED & RE-POSITIONED ABOVE GRID)
    let tooltip = document.getElementById('spark-image-magnifier-tooltip');
    if (!tooltip) {
        tooltip = document.createElement('div');
        tooltip.id = 'spark-image-magnifier-tooltip';
        tooltip.style.cssText = `
            position: fixed;
            pointer-events: none;
            display: none;
            z-index: 200000;
            width: 370px;
            height: 240px;
            border-radius: 8px;
            overflow: hidden;
            background: var(--card-bg);
            border: 2px solid var(--glow-color);
            box-shadow: 0 0 25px var(--glow-aura), 0 12px 35px rgba(0,0,0,0.85);
            transform: translate(-50%, -215px);
            transition: opacity 0.15s ease-out;
            opacity: 0;
        `;
        tooltip.innerHTML = `
            <img id="spark-magnifier-img" src="" style="width: 100%; height: 100%; object-fit: cover;">
            <div id="spark-magnifier-caption" style="position: absolute; bottom: 0; left: 0; right: 0; background: rgba(0,0,0,0.85); color: var(--glow-color); font-size: 9px; font-family: var(--branding-font); text-align: center; padding: 4px; text-transform: uppercase; letter-spacing: 1px;"></div>
        `;
        document.body.appendChild(tooltip);
    }

    const currentPrivacy = spark.privacy || 'public';

    // Concentric bands created via stacked alternating box-shadows (3px intervals)
    const concentricRingStyle = `
        position: relative;
        background: var(--card-bg);
        border-radius: 12px;
        box-shadow: 
            0 0 0 3px var(--bg-color),
            0 0 0 6px var(--glow-color),
            0 0 0 9px var(--bg-color),
            0 0 0 12px var(--glow-color),
            0 0 35px var(--glow-aura),
            0 15px 40px var(--card-shadow-color);
        margin: 16px;
    `;

    const abortBtnStyle = `
        transition: all 0.3s ease;
        border: 1px solid var(--branding-text-color);
        color: var(--branding-text-color);
        background: transparent;
        font-family: var(--branding-font);
        letter-spacing: 1px;
    `;

    editorOverlay.innerHTML = `
        <div class="hud-body-centered glass-3d w-full max-w-xl p-8" style="${concentricRingStyle}">
            <div style="display: flex; align-items: center; justify-content: center; gap: 10px; margin-bottom: 0.5rem;">
                <i class="fas fa-sliders-h" style="color: var(--glow-color); font-size: 1.2rem; filter: drop-shadow(0 0 8px var(--glow-color));"></i>
                <h2 class="hud-title-metallic" style="margin: 0; letter-spacing: 2px;">MODIFY SPARK</h2>
            </div>
            <hr class="metallic-divider w-full" style="border-color: var(--glow-aura); opacity: 0.6; margin-bottom: 1.5rem;">

            <div class="hud-input-group mt-4">
                <label class="hud-label-metallic" style="font-size: 10px; letter-spacing: 1.5px; opacity: 0.8;">INTERNAL IDENTITY (NAME)</label>
                <input type="text" id="edit-name-input" value="${spark.name}" class="hud-input" style="border: 1px solid var(--glow-aura); background: var(--bg-color-low); color: var(--branding-text-color);">
            </div>

            <div class="hud-input-group mt-3">
                <label class="hud-label-metallic" style="font-size: 10px; letter-spacing: 1.5px; opacity: 0.8;">VISIBILITY PROTOCOL (PRIVACY)</label>
                <select id="edit-privacy-select" class="hud-input" style="background: var(--bg-color-mid); color: var(--branding-text-color); border: 1px solid var(--glow-aura);">
                    <option value="public" ${currentPrivacy === 'public' ? 'selected' : ''}>PUBLIC</option>
                    <option value="unlisted" ${currentPrivacy === 'unlisted' ? 'selected' : ''}>UNLISTED</option>
                    <option value="private" ${currentPrivacy === 'private' ? 'selected' : ''}>PRIVATE</option>
                </select>
            </div>

            <div class="hud-input-group mt-3">
                <label class="hud-label-metallic" style="font-size: 10px; letter-spacing: 1.5px; opacity: 0.8;">CHOOSE COVER (HOVER TO MAGNIFY)</label>
                <div id="unsplash-grid" class="grid grid-cols-4 gap-3 mb-2 experiment-zone min-h-[120px]" style="border: 1px solid var(--glow-aura); padding: 8px; border-radius: 6px; background: var(--bg-color-low);">
                    <div class="col-span-4 text-center metallic-text py-10">Scanning Assets...</div>
                </div>
                <div id="attribution-label" class="hud-subtitle-info text-[10px] italic mb-6 min-h-[15px]" style="color: var(--glow-color); opacity: 0.8;"></div>
            </div>

            <div class="flex gap-4 w-full justify-center mt-6">
                <button onclick="window.closeSparkEditor()" 
                        class="ethereal-btn-xs px-8 py-2 rounded" 
                        style="${abortBtnStyle}"
                        onmouseover="this.style.background='var(--branding-text-color)'; this.style.color='var(--bg-color)';" 
                        onmouseout="this.style.background='transparent'; this.style.color='var(--branding-text-color)';">
                    ABORT
                </button>
                <button id="save-spark-changes" 
                        class="arcade-button px-10 py-2" 
                        style="box-shadow: 0 0 15px var(--glow-aura); font-family: var(--branding-font); letter-spacing: 1px;">
                    SAVE & SYNC
                </button>
            </div>
        </div>
    `;

    try {
        const searchQuery = spark.name || spark.template_type || spark.prompt || "technology";
        const apiImages = await fetchUnsplashCovers(searchQuery); 
        let images = [...apiImages];

        const types = databaseCache?.settings?.['arcade-current-types'] || {};
        
        const sparkIndex = spark.index !== undefined ? spark.index : 0;
        const defaultTemplate = types[sparkIndex] || Object.values(types).find(t => 
            t.name && spark.template_type && 
            t.name.toLowerCase().trim() === spark.template_type.toLowerCase().trim()
        );

        if (defaultTemplate && defaultTemplate.image) {
            images.unshift({
                url: defaultTemplate.image,
                photographer: "System Generated"
            });
        }

        const grid = document.getElementById('unsplash-grid');
        const attrLabel = document.getElementById('attribution-label');
        const tooltipImg = document.getElementById('spark-magnifier-img');
        const tooltipCap = document.getElementById('spark-magnifier-caption');
        
        if (grid) {
            grid.innerHTML = '';
            if (images.length > 0) {
                images.slice(0, 8).forEach(imgData => {
                    const img = document.createElement('img');
                    img.src = imgData.url; 
                    img.className = 'h-20 w-full object-cover cursor-pointer border-2 border-transparent hover:border-cyan-400 transition-all duration-300 shadow-lg rounded';
                    
                    if (spark.image === imgData.url) {
                        img.style.borderColor = 'var(--branding-color)';
                        attrLabel.textContent = `Photo By: ${imgData.photographer}`;
                    }

                    // --- HOVER MAGNIFIER LISTENERS ---
                    img.addEventListener('mouseenter', (e) => {
                        if (tooltipImg) tooltipImg.src = imgData.url;
                        if (tooltipCap) tooltipCap.textContent = `PREVIEW // ${imgData.photographer}`;
                        if (tooltip) {
                            tooltip.style.display = 'block';
                            tooltip.style.opacity = '1';
                        }
                    });

                    img.addEventListener('mousemove', (e) => {
                        if (tooltip) {
                            tooltip.style.left = `${e.clientX}px`;
                            tooltip.style.top = `${e.clientY}px`;
                        }
                    });

                    img.addEventListener('mouseleave', () => {
                        if (tooltip) {
                            tooltip.style.opacity = '0';
                            tooltip.style.display = 'none';
                        }
                    });

                    img.onclick = () => {
                        document.querySelectorAll('#unsplash-grid img').forEach(i => i.style.borderColor = 'transparent');
                        img.style.borderColor = 'var(--branding-color)';
                        attrLabel.textContent = `Photo By: ${imgData.photographer}`;
                        
                        window.selectedCover = imgData.url;
                        window.selectedPhotographer = imgData.photographer;
                    };
                    grid.appendChild(img);
                });
            } else {
                grid.innerHTML = `<div class="col-span-4 text-center metallic-text py-10">No Assets Found</div>`;
            }
        }
    } catch (e) {
        console.warn("[SYSTEM] Asset API Offline.");
    }

    document.getElementById('save-spark-changes').onclick = async () => {
        const newName = document.getElementById('edit-name-input').value;
        const newPrivacy = document.getElementById('edit-privacy-select').value;
        const params = new URLSearchParams(window.location.search);
        
        const realmId = params.get('realm');
        const currentId = params.get('current');
        const sparkId = params.get('spark') || spark.id;

        if (!realmId || !currentId || !sparkId) {
            console.error("[CRITICAL] Missing identifiers for DB sync.");
            return;
        }

        const updateData = {
            ...spark,
            name: newName,
            privacy: newPrivacy
        };

        if (window.selectedCover) {
            updateData.image = window.selectedCover;
            updateData.photographer = window.selectedPhotographer; 
        }

        const dbPath = `realms/${realmId}/currents/${currentId}/sparks/${sparkId}`;
        
        try {
            await saveToRealtimeDB(dbPath, updateData);
            
            spark.name = updateData.name;
            spark.privacy = updateData.privacy;
            if (window.selectedCover) {
                spark.image = updateData.image;
                spark.photographer = updateData.photographer;
            }

            const activeHeader = document.getElementById('active-spark-name');
            if (activeHeader) activeHeader.textContent = newName;
            
            window.closeSparkEditor();
            
            window.selectedCover = null;
            window.selectedPhotographer = null;
            const hudStatus = document.getElementById('hud-status');
            if (hudStatus) hudStatus.textContent = "SPARK CHANGES UPDATED...";
        } catch (error) {
            console.error("[DATABASE] Sync Failure:", error);
        }
    };
}

/* FETCH UNSPLASH COVERS */
async function fetchUnsplashCovers(query) {
    const ACCESS_KEY = databaseCache?.app_manifest?.unsplashkey; 
    
    if (!ACCESS_KEY) {
        console.warn("[SYSTEM] Unsplash Key missing from databaseCache.");
        return [];
    }

    const url = `https://api.unsplash.com/search/photos?query=${encodeURIComponent(query)}&per_page=12&orientation=landscape&client_id=${ACCESS_KEY}`;

    try {
        const response = await fetch(url);
        if (!response.ok) return [];

        const dataResult = await response.json();
        
        if (dataResult && dataResult.results) {
            return dataResult.results.map(img => ({
                url: img.urls.regular,
                photographer: img.user.name 
            }));
        }
        return [];
        
    } catch (error) {
        console.error("[SYSTEM] Network Error:", error);
        return [];
    }
}
