import { getArcadeData, saveToRealtimeDB } from '/config/firebase-config.js';
import { watchAuthState } from '/config/auth.js';
import { globalTheme, applyTheme, databaseCache } from './arcade.js';

let allSparks = [];
let currentIndex = -1;
let currentId = '';
let userId = '';

console.log(`%c YERTAL SPARKS LOADED | ${new Date().toLocaleDateString()} @ 15:38:00 `, "background: var(--branding-color); color: var(--bg-color); font-weight: bold; border: 1px solid var(--branding-color); padding: 4px;");
/*
 * Objective: Capture live UI state from the simulation iframe.
 * Task: Directly update the spark object's parameter_map with current UI values.
 */
function syncUIToSessionMap(spark) {
    console.group("%c[SYNC DEBUG] 🔍 Distilling UI to Spark Object...", "color: #ffca28; font-weight: bold;");

    const settings = databaseCache?.settings || {};
    const blueprints = settings["arcade-current-types"];
    const blueprint = Array.isArray(blueprints) ? blueprints[spark.index] : null;

    if (!blueprint || !blueprint.parameter_map) {
        console.warn("[SYNC] ❌ No blueprint schema found for index:", spark.index);
        console.groupEnd();
        return;
    }

    const iframeDoc = document.getElementById('content-frame')?.contentWindow?.document;
    if (!iframeDoc) {
        console.error("[SYNC] ❌ Critical: Cannot access iframe document.");
        console.groupEnd();
        return;
    }

    // Ensure the spark has a parameter_map to write to
    if (!spark.parameter_map) spark.parameter_map = {};

    const schemaKeys = Object.keys(blueprint.parameter_map);
    
    schemaKeys.forEach(key => {
        const input = iframeDoc.getElementById(key);
        if (input) {
            let val = input.value;
            const type = input.type;

            // Type-specific extraction
            if (type === 'range' || type === 'number' || type === 'hidden') {
                val = parseFloat(val);
            } else if (type === 'checkbox') {
                val = input.checked;
            }

            // DIRECT MUTATION: Update the spark memory object
            if (spark.parameter_map[key] !== val) {
                console.log(`%c[SYNC] Update: ${key} | ${spark.parameter_map[key]} -> ${val}`, "color: #4caf50; font-weight: bold;");
                spark.parameter_map[key] = val;
            }
        }
    });

    console.log("[SYNC] Distillation Complete. Spark Memory is now current.");
    console.groupEnd();
}

/*
 * Standardizes raw Spark code to fit the responsive Laboratory Viewport.
 * @param {Object} spark - The spark data object from the DB.
 * @returns {string} - The complete HTML string for the iframe.
 */
function wrapCodeInLaboratory(spark) {
    const activeCode = spark.code || (spark.data ? spark.data.code : null) || spark.html || (typeof spark === 'string' ? spark : "");

    return `
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <style>
                /* Prevent the 'Double Scrollbar' and Clipping */
                body, html { 
                    margin: 0; 
                    padding: 0; 
                    width: 100%; 
                    height: 100%; 
                    overflow: hidden; /* Critical: Stops the Spark from overflowing the Lab */
                    background: transparent; 
                    display: flex; 
                    flex-direction: column;
                }

                #user-code-wrapper {
                    flex: 1; /* Occupies all available space in the Lab */
                    width: 100%;
                    height: 100%;
                    display: flex;
                    flex-direction: column;
                    justify-content: center;
                    align-items: center;
                    position: relative;
                    box-sizing: border-box;
                }

                /* Standardizes any canvas generated by Gemini to fit within the viewport */
                #user-code-wrapper canvas { 
                    max-width: 100% !important; 
                    max-height: 100% !important;
                    object-fit: contain; 
                    box-sizing: border-box;
                }
            </style>
        </head>
        <body>
            <div id="user-code-wrapper">
                ${activeCode}
            </div>

            <script>
                (function() {
                    const wrapper = document.getElementById('user-code-wrapper');

                    function syncDimensions() {
                        const canvases = document.querySelectorAll('canvas');
                        const bounds = wrapper.getBoundingClientRect();

                        canvases.forEach(canvas => {
                            // If the canvas is the main element, sync its resolution to the Lab Stage
                            // This fixes the "Cut off" issue by ensuring internal resolution = visual size
                            if (canvas.width !== bounds.width || canvas.height !== bounds.height) {
                                // Save current drawing to prevent flicker/loss
                                const tempCtx = canvas.getContext('2d');
                                let tempImage = null;
                                if (tempCtx) {
                                    tempImage = canvas.toDataURL();
                                }

                                canvas.width = bounds.width;
                                canvas.height = bounds.height;

                                if (tempImage) {
                                    const img = new Image();
                                    img.src = tempImage;
                                    img.onload = () => canvas.getContext('2d').drawImage(img, 0, 0, bounds.width, bounds.height);
                                }
                            }
                        });

                        // Notify internal scripts (Three.js/P5) that the Lab has resized
                        window.dispatchEvent(new Event('resize'));
                    }

                    // ResizeObserver is more reliable than window.onresize for iframe/container changes
                    const ro = new ResizeObserver(() => {
                        requestAnimationFrame(syncDimensions);
                    });

                    ro.observe(wrapper);

                    // Initial sync once everything is parsed
                    window.addEventListener('load', syncDimensions);
                })();
            </script>
        </body>
        </html>
    `;
}
/*
 * Objective: Render Spark content and reset HUD visuals.
 * Task: Initialize playable states and reset timing/progress for the new session.
 */
function loadSpark(spark) {
    const container = document.getElementById('spark-content-container');
    const titleEl = document.getElementById('active-spark-name');
    const overlay = document.getElementById('spark-title-overlay');
    const hudStatus = document.getElementById('hud-status');
    const fallbackBtn = document.getElementById('fallback-url-btn');
    
    // 0. HUD CONTROL INITIALIZATION
    window.currentSpark = spark;
    const playPauseBtn = document.getElementById('play-pause-btn');
    const playIcon = document.getElementById('play-icon');
    const curTimeEl = document.getElementById('current-time');
    const totTimeEl = document.getElementById('total-duration');
    const progressFill = document.getElementById('media-progress-bar');

    // CRITICAL FOR TIMING: Reset visuals to zero state immediately
    if (curTimeEl) curTimeEl.textContent = "0:00";
    if (totTimeEl) totTimeEl.textContent = "0:00";
    if (progressFill) progressFill.style.width = "0%";

    // Intelligent Type Detection
    const playableIDs = ['movies', 'videos', 'veo-video', 'arcade-logic', 'games', 'physics-lab', 'optics'];
    const isPlayable = playableIDs.includes(spark.template_type?.toLowerCase()) || 
                       (spark.link && (spark.link.includes('youtube.com') || spark.link.includes('vimeo.com')));

    if (playPauseBtn) {
        playPauseBtn.style.opacity = isPlayable ? '1' : '0.3';
        playPauseBtn.style.pointerEvents = isPlayable ? 'auto' : 'none';
        
        // Default to 'Pause' icon because simulations/videos usually autoplay
        if (playIcon) {
            playIcon.classList.remove('fa-play');
            playIcon.classList.add('fa-pause');
        }
    }

    // 1. IDENTITY & THEME
    if (typeof databaseCache !== 'undefined') {
        applyTheme(globalTheme);
    }
    
    console.log(`%c[YERTAL LAB] Loading Spark: ${spark.name}`, "color: #00f2ff; font-weight: bold;");
        
    container.style.opacity = '0';
    container.innerHTML = '';
    if (hudStatus) hudStatus.textContent = "INITIALIZING...";

    titleEl.textContent = spark.name;
    overlay.style.opacity = "1";
    setTimeout(() => { overlay.style.opacity = "0"; }, 3000);

    // 2. CONTENT INJECTION
    if (spark.link) {
        let finalUrl = spark.link;
        if (finalUrl.includes('youtube.com/watch?v=')) {
            finalUrl = finalUrl.replace('watch?v=', 'embed/') + "?autoplay=1&mute=1&enablejsapi=1";
        }
        
        container.innerHTML = `<iframe id="content-frame" src="${finalUrl}" allow="autoplay; fullscreen"></iframe>`;
        container.style.opacity = '1';
        
    } else {
        const iframe = document.createElement('iframe');
        iframe.id = "content-frame";
        // allow-same-origin is critical for persistence if scripts interact with parent
        iframe.setAttribute('sandbox', 'allow-scripts allow-same-origin allow-forms');
        
        container.appendChild(iframe);

        // Wrap the code
        const standardizedCode = wrapCodeInLaboratory(spark);
        
        /*
         * REVERT TO DOCUMENT.WRITE:
         * Using the fixed template (block comments only), document.write provides 
         * the most stable injection method for dynamic hydration.
         */
        try {
            const doc = iframe.contentWindow.document;
            doc.open();
            doc.write(standardizedCode);
            doc.close();
        } catch (err) {
            console.error("[SYSTEM] Document write failed:", err);
        }

        if (fallbackBtn) fallbackBtn.classList.add('hidden');

        iframe.onload = () => {
            container.style.opacity = '1';
            if (hudStatus) hudStatus.textContent = "SPARK FULLY LOADED";
        };
    }
}

/*
 * Objective: Change viewports to adjacent spark structures.
 * Task: Maintain state continuity across transitions by preserving realm configuration URL parameters.
 */
function navigate(dir) {
    currentIndex = (currentIndex + dir + allSparks.length) % allSparks.length;
    
    const nextSpark = allSparks[currentIndex];
    
    // Highlighted changes to apply: Read and preserve the active user slug
    const currentParams = new URLSearchParams(window.location.search);
    const userParam = currentParams.get('user');
    
    // Highlighted changes to apply: Conditionally append user back into the string
    let newUrl = `${window.location.pathname}?current=${currentId}&spark=${nextSpark.id}`;
    if (userParam) {
        newUrl += `&user=${userParam}`;
    }
    
    window.history.pushState({path: newUrl}, '', newUrl);
    console.log(`navigation detected direction=${dir} currentIndex=${currentIndex}`);
    
    const freshlyAssembled = assembleSpark(nextSpark);
    window.currentSpark = freshlyAssembled;
    loadSpark(freshlyAssembled);
}

function toggleZen() {
    document.body.classList.toggle('zen-active');
}

function togglePlayPause() {
    window.dispatchEvent(new CustomEvent('toggleMedia'));
    const icon = document.getElementById('play-icon');
    if (icon) {
        icon.classList.toggle('fa-play');
        icon.classList.toggle('fa-pause');
    }
}

/*
 * Objective: Initialize HUD and navigation interactions.
 * Task: Restrict navigation to mouse-only via side zones and reserve arrow keys for viewport gameplay.
 * Task: Integrate Session Map resets on navigation and exit.
 */
function setupInteractions(currentUid, spark) {
    // 1. Navigation: Mouse-Only via side zones
    const prevZone = document.getElementById('prev-zone');
    const nextZone = document.getElementById('next-zone');

    if (prevZone) {
        prevZone.onclick = (e) => {
            e.stopPropagation();
            e.preventDefault();
            console.log("[NAV] Navigating to Previous Spark...");
            navigate(-1);
        };
    }

    if (nextZone) {
        nextZone.onclick = (e) => {
            e.stopPropagation();
            e.preventDefault();
            console.log("[NAV] Navigating to Next Spark...");
            navigate(1);
        };
    }

    // 2. HUD & Cover Bindings
    const editBtn = document.getElementById('edit-spark-btn');

    if (editBtn) {
        const isOwner = currentUid && spark && spark.owner === currentUid;
        const isSuperUser = currentUid === 'yertal-arcade';

        if (isOwner || isSuperUser) {
            editBtn.style.display = 'flex';
            editBtn.onclick = (e) => {
                e.stopPropagation();
                openSparkEditor(window.currentSpark || spark);
            };
        } else {
            editBtn.style.display = 'none';
        }
    }

    // 3. UI Toggles & Media Controls
    const zenBtn = document.getElementById('zen-btn');
    if (zenBtn) zenBtn.onclick = toggleZen;

    const exitZenBtn = document.getElementById('exit-zen-btn');
    if (exitZenBtn) {
        exitZenBtn.onclick = (e) => {
            e.stopPropagation();
            toggleZen();
        };
    }

    const playPauseBtn = document.getElementById('play-pause-btn');
    if (playPauseBtn) {
        playPauseBtn.onclick = (e) => {
            e.stopPropagation();
            togglePlayPause();
        };
    }

    const contentContainer = document.getElementById('spark-content-container');
    if (contentContainer) {
        contentContainer.onclick = (e) => {
            togglePlayPause();
        };
    }

    // 4. Reload Logic: Now tracking window.currentSpark dynamically
    const reloadBtn = document.getElementById('reload-spark-btn');
    if (reloadBtn) {
        reloadBtn.onclick = () => {
            const activeSpark = window.currentSpark || spark;
            if (activeSpark) {
                console.group("🔄 RELOAD AUDIT");
                // 1. Sync
                syncUIToSessionMap(activeSpark);
                // 2. Assemble
                const freshlyAssembledSpark = assembleSpark(activeSpark);
                // 3. Load
                window.currentSpark = freshlyAssembledSpark;
                loadSpark(freshlyAssembledSpark);
                console.groupEnd();
            }
        };
    }

    // 5. Fallback URL Binding
    const fallbackBtn = document.getElementById('fallback-url-btn');
    if (fallbackBtn) {
        fallbackBtn.onclick = () => {
            const activeSpark = window.currentSpark || spark;
            if (activeSpark && activeSpark.link) {
                window.open(activeSpark.link, '_blank');
            }
        };
    }

    // 6. Exit Logic: Return to Showroom
    const exitBtn = document.getElementById('exit-btn');
    if (exitBtn) {
        exitBtn.addEventListener('click', (e) => {
            e.preventDefault();
            e.stopPropagation();

            const params = new URLSearchParams(window.location.search);
            const userSlug = params.get('user') || 'yertal-arcade';

            const container = document.getElementById('spark-content-container');
            if (container) container.innerHTML = '';

            console.log("[SYSTEM] Exiting to Showroom...");
            window.location.href = `/arcade/index.html?user=${userSlug}`;
        }, true);
    }

    // 8. Keyboard Shortcuts
    window.onkeydown = (e) => {
        const key = e.key.toLowerCase();

        if (key === 'z' || key === 'escape') {
            toggleZen();
        }

        // Ctrl+R Logic: Now tracks live global target execution context
        if (key === 'r' && e.ctrlKey) {
            e.preventDefault();
            const activeSpark = window.currentSpark || spark;
            if (activeSpark) {
                syncUIToSessionMap(activeSpark);
                const freshlyAssembled = assembleSpark(activeSpark);
                window.currentSpark = freshlyAssembled;
                loadSpark(freshlyAssembled);
            }
        }

        if (key === ' ' && e.target.tagName !== 'INPUT' && e.target.tagName !== 'TEXTAREA') {
            e.preventDefault();
            togglePlayPause();
        }
    };

    // 9. Auto-Focus Viewport
    const iframe = document.querySelector('#spark-content-container iframe');
    if (iframe) iframe.focus();
}

/*
 * Objective: Hydrate a blueprint template with the established hierarchy of truth.
 * Task: Ensure session values (Layer 3) take absolute precedence during string replacement.
 */
function assembleSpark(spark) {
    // Highlighted changes to apply:
    if ((spark.code || spark.link) && (spark.index === undefined || spark.index === null)) {
        return spark;
    }

    const settings = databaseCache?.settings || {};
    const blueprints = settings["arcade-current-types"];
    const blueprint = Array.isArray(blueprints) ? blueprints[spark.index] : null;

    if (!blueprint) {
        console.error(`[ASSEMBLER] ❌ FAILED: No blueprint found at index: ${spark.index}`);
        return spark;
    }

    // --- THE HIERARCHY OF TRUTH ---
    // Layer 1: Blueprint Defaults
    // Layer 2: User Spark Node (Saved state)
    // Layer 3: Live Session (Current UI state)
    const finalParameters = { 
        ...(blueprint.parameter_map || {}), 
        ...(spark.parameter_map || {})
    };

    console.groupCollapsed(`[ASSEMBLER] 🛠️ Assembling: ${spark.name}`);
    console.log("Hierarchy Result:", finalParameters);

    let hydratedCode = blueprint.template || "";

    if (hydratedCode) {
        // Iterate through the keys defined in the BLUEPRINT to ensure we don't miss anything
        const schemaKeys = Object.keys(blueprint.parameter_map || finalParameters);
        
        schemaKeys.forEach(key => {
            let value = finalParameters[key];

            // Handle Arrays/Objects
            if (value !== null && typeof value === 'object') {
                value = JSON.stringify(value).replace(/"/g, "'").replace(/'/g, "&apos;");
            }

            const regex = new RegExp(`{{\\s*${key}\\s*(?:\\|\\|\\s*[^}]+)?}}`, 'g');
            
            if (hydratedCode.match(regex)) {
                // This is the moment of truth: check the log for this specific replacement
                console.log(`[BAKING] {{${key}}} -> ${value}`);
                hydratedCode = hydratedCode.replace(regex, () => value);
            }
        });
    }

    console.groupEnd();

    // We return a NEW object to avoid mutating the original reference too early
    return {
        ...spark,
        code: hydratedCode,
        parameter_map: finalParameters 
    };
}


watchAuthState(async (user) => {
    console.log("%c[AUTH] State Changed", "color: #00ff00;");
    if (!user) return;

    userId = user.uid; 
    // load the spark for the user, current, spark defined in the URL
    const params = new URLSearchParams(window.location.search);
    const pageOwnerSlug = params.get('user'); 
    currentId = params.get('current');
    const initialSparkId = params.get('spark');

    // 1. Helper to scan the cache
    const findOwnerInCache = (data) => {
        const users = data?.users || {};
        // Check for explicit slug match OR fallback to the superuser ID
        return Object.keys(users).find(uid => {
            const profile = users[uid].profile || {};
            return profile.slug === pageOwnerSlug || uid === 'yertal-arcade';
        });
    };

    let ownerUid = findOwnerInCache(databaseCache);

    // 2. Fetch if missing
    if (!databaseCache || Object.keys(databaseCache).length === 0 || !ownerUid) {
        console.log("[CACHE] Cache miss for owner:", pageOwnerSlug, ". Fetching...");
        const freshData = await getArcadeData(); 
        ownerUid = findOwnerInCache(freshData);
    }

// 3. RESOLUTION LOGIC REFINEMENT
const targetUid = ownerUid || userId;
let userRecord = databaseCache?.users?.[targetUid];

// Logic change: If targetUid is found but infrastructure is missing, 
// it's likely a partial cache. Force a refresh.
if (!userRecord || !userRecord.infrastructure) {
    console.log("[SYSTEM] Infrastructure missing for:", targetUid, ". Requesting sync...");
    const freshData = await getArcadeData(); // This should hit the actual DB
    userRecord = freshData?.users?.[targetUid];
}

// Ensure the specific current exists
const currents = userRecord?.infrastructure?.currents || {};
const path = currents[currentId];

if (!path) {
    // Fallback: If 'neural-void' isn't found, try to grab the first available current
    const fallbackCurrent = Object.values(currents)[0];
    if (fallbackCurrent) {
        console.warn("[DATA] Redirecting to fallback current infrastructure.");
        path = fallbackCurrent;
    } else {
        console.error("[DATA] No record for current:", currentId);
        return;
    }
}

    // 4. Load the Spark
    const sparksObj = path.sparks || {};
    allSparks = Object.values(sparksObj).sort((a, b) => (a.created || 0) - (b.created || 0));
    
    // Use the ID from the URL or fallback to the first one
    currentIndex = allSparks.findIndex(s => s.id === initialSparkId);

    let activeSpark = null;
    if (currentIndex !== -1) {
        activeSpark = allSparks[currentIndex];
    } else if (allSparks.length > 0) {
        activeSpark = allSparks[0];
    }
    if (activeSpark) {
        // NEW: Assemble the spark before loading
        const preparedSpark = assembleSpark(activeSpark);
        loadSpark(preparedSpark);
    } else {
        document.getElementById('active-spark-name').textContent = "EMPTY CURRENT";
    }
    setupInteractions(user.uid, activeSpark);
});

window.addEventListener('message', (event) => {
    // 1. Security check: Ensure we have data
    if (!event.data || event.data.type !== 'TICKER_UPDATE') return;

    const { currentTime, duration } = event.data;
    
    // 2. Select the HTML elements from your spark.html
    const curTimeEl = document.getElementById('current-time');
    const totTimeEl = document.getElementById('total-duration');
    const progressFill = document.getElementById('media-progress-bar');

    // 3. Formatter: Converts seconds (65) to string (01:05)
    const format = (seconds) => {
        const mins = Math.floor(seconds / 60);
        const secs = Math.floor(seconds % 60);
        return `${mins}:${secs.toString().padStart(2, '0')}`;
    };

    // 4. Update the HUD
    if (curTimeEl) curTimeEl.textContent = format(currentTime);
    if (totTimeEl) totTimeEl.textContent = format(duration);
    
    if (progressFill && duration > 0) {
        const percent = (currentTime / duration) * 100;
        progressFill.style.width = `${percent}%`;
    }
});

async function openSparkEditor(spark) {
    if (!spark) return;

    // 1. RESET GLOBAL SELECTIONS to prevent data-bleeding between sparks
    window.selectedCover = null;
    window.selectedPhotographer = null;

    let editorOverlay = document.getElementById('spark-editor-modal');
    if (!editorOverlay) {
        editorOverlay = document.createElement('div');
        editorOverlay.id = 'spark-editor-modal';
        editorOverlay.style.cssText = `
            position: fixed; top: 0; left: 0; width: 100vw; height: 100vh;
            background: rgba(0, 0, 0, 0.85); backdrop-filter: blur(8px);
            display: flex; justify-content: center; align-items: center; z-index: 10000;
        `;
        document.body.appendChild(editorOverlay);
    }

    editorOverlay.innerHTML = `
        <div class="hud-body-centered glass-3d w-full max-w-xl p-8">
            <h2 class="hud-title-metallic">Modify Spark</h2>
            <hr class="metallic-divider w-full">

            <div class="hud-input-group mt-4">
                <label class="hud-label-metallic">Internal Identity (Name)</label>
                <input type="text" id="edit-name-input" value="${spark.name}" class="hud-input">
            </div>

            <div class="hud-input-group">
                <label class="hud-label-metallic">Choose Cover</label>
                <div id="unsplash-grid" class="grid grid-cols-4 gap-3 mb-2 experiment-zone min-h-[120px]">
                    <div class="col-span-4 text-center metallic-text py-10">Scanning Assets...</div>
                </div>
                <div id="attribution-label" class="hud-subtitle-info text-[10px] italic mb-6 min-h-[15px]"></div>
            </div>

            <div class="flex gap-4 w-full justify-center">
                <button onclick="document.getElementById('spark-editor-modal').remove()" 
                        class="ethereal-btn-xs">ABORT</button>
                <button id="save-spark-changes" 
                        class="arcade-button px-10">SAVE & SYNC</button>
            </div>
        </div>
    `;

    try {
        const searchQuery = spark.name || spark.template_type || spark.prompt || "technology";
        const apiImages = await fetchUnsplashCovers(searchQuery); 
        let images = [...apiImages];

        // --- FIND AND INSERT DEFAULT TEMPLATE IMAGE ---
        const types = databaseCache?.settings?.['arcade-current-types'] || {};
        // Note: Corrected to toLowerCase() and checked for existence of spark.template_type
        const defaultTemplate = Object.values(types).find(t => 
            t.name && spark.template_type && 
            t.name.toLowerCase().trim() === spark.template_type.toLowerCase().trim()
        );

        console.log("spark.js: openSparkEditor: spark.image URL=", defaultTemplate.image);
        
        if (defaultTemplate && defaultTemplate.image) {
            images.unshift({
                url: defaultTemplate.image,
                photographer: "System Generated"
            });
        }
        // ----------------------------------------------

        const grid = document.getElementById('unsplash-grid');
        const attrLabel = document.getElementById('attribution-label');
        
        if (grid) {
            grid.innerHTML = '';
            if (images.length > 0) {
                images.slice(0, 8).forEach(imgData => {
                    const img = document.createElement('img');
                    img.src = imgData.url; 
                    img.className = 'h-20 w-full object-cover cursor-pointer border-2 border-transparent hover:border-cyan-400 transition-all duration-300 shadow-lg';
                    
                    if (spark.image === imgData.url) {
                        img.style.borderColor = 'var(--branding-color)';
                        attrLabel.textContent = `Photo By: ${imgData.photographer}`;
                    }

                    img.onclick = () => {
                        document.querySelectorAll('#unsplash-grid img').forEach(i => i.style.borderColor = 'transparent');
                        img.style.borderColor = 'var(--branding-color)';
                        attrLabel.textContent = `Photo By: ${imgData.photographer}`;
                        
                        window.selectedCover = imgData.url;
                        window.selectedPhotographer = imgData.photographer;
                    };
                    grid.appendChild(img);
                });
            } else {
                grid.innerHTML = `<div class="col-span-4 text-center metallic-text py-10">No Assets Found</div>`;
            }
        }
    } catch (e) {
        console.warn("[SYSTEM] Asset API Offline.");
    }

    document.getElementById('save-spark-changes').onclick = async () => {
        const newName = document.getElementById('edit-name-input').value;
        const params = new URLSearchParams(window.location.search);
        
        const currentId = params.get('current');
        const sparkId = params.get('spark') || spark.id;

        if (!currentId || !sparkId) {
            console.error("[CRITICAL] Missing identifiers for DB sync.");
            return;
        }

        // 2. PROTECT DATA: Construct a clean update object
        // This ensures we only change specific fields and don't overwrite template_type accidentally
        const updateData = {
            ...spark, // Start with original data
            name: newName
        };

        if (window.selectedCover) {
            updateData.image = window.selectedCover;
            updateData.photographer = window.selectedPhotographer; 
        }

        const dbPath = `users/${spark.owner}/infrastructure/currents/${currentId}/sparks/${sparkId}`;
        
        try {
            await saveToRealtimeDB(dbPath, updateData);
            
            // Sync local state
            spark.name = updateData.name;
            if (window.selectedCover) {
                spark.image = updateData.image;
                spark.photographer = updateData.photographer;
            }

            const activeHeader = document.getElementById('active-spark-name');
            if (activeHeader) activeHeader.textContent = newName;
            
            document.getElementById('spark-editor-modal').remove();
            
            // 3. CLEAN UP globals after successful save
            window.selectedCover = null;
            window.selectedPhotographer = null;
            const hudStatus = document.getElementById('hud-status');
            if (hudStatus) hudStatus.textContent = "SPARK CHANGES UPDATED...";
        } catch (error) {
            console.error("[DATABASE] Sync Failure:", error);
        }
    };
}

async function fetchUnsplashCovers(query) {
    const ACCESS_KEY = databaseCache?.app_manifest?.unsplashkey; 
    
    if (!ACCESS_KEY) {
        console.warn("[SYSTEM] Unsplash Key missing from databaseCache.");
        return [];
    }

    const url = `https://api.unsplash.com/search/photos?query=${encodeURIComponent(query)}&per_page=12&orientation=landscape&client_id=${ACCESS_KEY}`;

    try {
        const response = await fetch(url);
        if (!response.ok) return [];

        const dataResult = await response.json();
        
        if (dataResult && dataResult.results) {
            return dataResult.results.map(img => ({
                url: img.urls.regular,
                photographer: img.user.name 
            }));
        }
        return [];
        
    } catch (error) {
        console.error("[SYSTEM] Network Error:", error);
        return [];
    }
}
